# Generated by Django 5.2.13 on 2026-04-20 16:05

import wagtail_honeypot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_testapp", "0003_formfield_formpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpage",
            name="honeypot",
            field=models.BooleanField(
                default=wagtail_honeypot.models.get_honeypot_default,
                verbose_name="Honeypot enabled",
            ),
        ),
    ]
